### Register a new client 
### ('redirect_uri' param is registered as the default one; It is used only when redirect_uri is not provided in the oauth process)
POST http://localhost:8081/register
Content-Type: application/x-www-form-urlencoded

name=client_test&redirect_uri=https://localhost/auth?provider=app

### Authorization interface
GET http://localhost:8081/auth?response_type=code&client_id=client_60e0f6386ed629.76065327&scope=profile&state=random

### Request authorization code
GET http://localhost:8081/auth-Oui?client_id=client_60e0f6386ed629.76065327&state=random

### Request token authorization code
GET http://localhost:8081/token?grant_type=authorization_code&code=XXXXXX&client_id=client_60e0f6386ed629.76065327&client_secret=d288a9a9cc9336f9bcee7ba89fb7f1485b5b9e24